# Generated by Django 4.0.4 on 2022-04-20 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_actor_image'),
        ('movies', '0004_alter_movie_image'),
        ('casts', '0002_cast_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.actor'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
