# Generated by Django 4.0.4 on 2022-04-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='actors')),
                ('date_of_brith', models.DateField()),
                ('debut', models.DateField(blank=True, null=True)),
                ('debut_movie', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
