# Generated by Django 4.0.4 on 2022-04-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_actor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='date_of_brith',
            new_name='date_of_birth',
        ),
    ]
