# Generated by Django 4.0.4 on 2022-04-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_rename_date_of_brith_actor_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(default='', upload_to='actor_image'),
        ),
    ]
