# Generated by Django 4.0.4 on 2022-04-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('language', models.CharField(choices=[('EN', 'ENGLISH'), ('HI', 'HINDI'), ('TA', 'TAMIL'), ('TE', 'TELUGU')], max_length=2)),
                ('image', models.ImageField(upload_to='movies')),
                ('date_of_release', models.DateField()),
                ('actors_count', models.IntegerField(default=0)),
            ],
        ),
    ]
