# Generated by Django 4.0.4 on 2022-04-18 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AC', 'ACTION'), ('DR', 'DRAMA'), ('RO', 'ROMANCE'), ('CO', 'COMEDY'), ('TH', 'THRILLER')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors_count',
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='movies_thumbnails'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre', to='movies.genre'),
        ),
    ]
